version: '3' 
services:
 client:
   build: ./GestionEventFrontend/
   ports:
     - "80:4200"
 server: 
   build: .
   ports:
     - "8080:8080"
   environment:
     - MONGO_URL=mongodb://database/Event
   links:
     - database
   depends_on:
     - database
 database: 
   image: mongo
   volumes:
     - "/data/db:/data/db"
   ports:
     - "27017:27017" 
